// Re-export the unified protocol types from the extension host's single source
// of truth. Keeping one definition ensures webview and host never drift.
export type {
  JsonRpcRequest,
  JsonRpcResponse,
  JsonRpcNotification,
  TextParams,
  ThinkParams,
  ToolCallParams,
  ToolResultParams,
  ToolStreamParams,
  CompactStartParams,
  CompactEndParams,
  SystemParams,
  UserMessageParams,
  AssistantToolCall,
  AssistantMessageParams,
  ErrorParams,
  ConfigParams,
  WorkspaceStateParams,
  Workspace,
  WorkspaceSession,
  InjectedParams,
  FileChangesParams,
  FileChangeEntry,
  RequiredPermissionParams,
  PermissionRequestParams,
  PermissionApproveParams,
  QuestionOptionParams,
  QuestionItemParams,
  UserQuestionParams,
  QuestionAnswerParams,
  UserAnswerParams,
  UsageParams,
  TodoParams,
  TodoItem,
  TurnStatsParams,
  SlashCommand,
  UiMessageParams,
  ConfigModel,
  ConfigView,
} from '../../src/protocol';
