[package]
name = "arrow-coder-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
async-stream = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
hex = { workspace = true }
html5ever = { workspace = true }
markup5ever_rcdom = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
grep = { workspace = true }
lazy_static = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
termcolor = { workspace = true }
toml = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }
which = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
